include $(srctree)/drivers/misc/mediatek/Makefile.custom

ifeq ($(CONFIG_ARCH_MTK_PROJECT),"oppo6755_15101")
obj-y += $(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/
else
obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/
endif



