
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_YAS532),y)
obj-y	+=  yamaha532/
endif

ifeq ($(CONFIG_MTK_YAS532_NEW),y)
obj-y	+=  yamaha532-new/
endif

ifeq ($(CONFIG_MTK_YAS533_NEW),y)
obj-y	+=  yamaha533-new/
endif

ifeq ($(CONFIG_MTK_MMC3416X_NEW),y)
obj-y	+=  mmc3416x-new/
endif

ifeq ($(CONFIG_MTK_AKM8963_NEW),y)
obj-y	+=  akm8963-new/
endif

ifeq ($(CONFIG_MTK_AKM09911_NEW),y)
obj-y	+=  akm09911-new/
endif

ifeq ($(CONFIG_MTK_YAS537),y)
obj-y	+=  yamaha537/
endif

ifeq ($(CONFIG_MTK_MMC3530X),y)
obj-y	+=  mmc3530x/
endif