
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-y += -Werror
obj-y += oppo16021_hx8394_boe_hd720_dsi_vdo.o
#obj-y += tps65132.o
#obj-y += Bl_lm3630a.o




