
ifeq ($(CONFIG_FINGERPRINT_CHIP), "fpc1020")
obj-y	+= fpc1020/
endif

ifeq ($(CONFIG_FINGERPRINT_CHIP), "fpc1021")
obj-y	+= fpc1021/
endif

ifeq ($(CONFIG_FINGERPRINT_CHIP), "fpc1145")
obj-y	+= fpc1145/
endif


