
include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Module project related part

ifeq ($(CONFIG_MTK_CM36652_NEW),y)
obj-y	+=  cm36652-new/
endif

#VENDOR_EDIT
ifeq ($(CONFIG_MTK_APDS9921_NEW),y)
obj-y	+=  apds9921-new/
endif

ifeq ($(CONFIG_MTK_CM36686_NEW),y)
obj-y	+=  cm36686-new/
endif
