
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-y += -Werror
obj-y += oppo_jdi_r63452_fhd1080_dsi_cmd.o
obj-y += tps65132.o
obj-y += Bl_lm3630a.o
obj-y += Bl_lm3697.o




