include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_RTC) += mtk_rtc_common.o

obj-y += mt6353/

#obj-$(CONFIG_MTK_PMIC_CHIP_MT6353) += mt6353/

#obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/