# ----------------------------------------------------------------------------- 
# export these for cross compiling
# export ARCH=arm64
# export CROSS_COMPILE=arm-linux-eabi-
# export KERNELDIR=/extra/android50_msm8994/kernel
# ----------------------------------------------------------------------------- 
include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y += fpc_irq.o
obj-y += fpc_spi.o
