
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-y += -Werror
obj-y += ili9881c_fhd720_dsi_vdo_boe.o
obj-y += tps65132.o
obj-y += Bl_lm3630a.o




