include $(srctree)/drivers/misc/mediatek/Makefile.custom

# In case the platform does NOT support this type of sensors
obj-y	+=	rgb_core.o

obj-$(CONFIG_MTK_TCS3490)	+=  tcs3490/
obj-$(CONFIG_MTK_NXU8010)	+=  nxu8010/

